spring:
  config:
    import: optional:dotenv:./.env #  env ?? ???? ?(Optinal ? ??? ??X)

  profiles:
    active:
      - dev # ??? profile

  application:
    name: monew # ?????? ??

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul # ??? ?????(ms) ? ??? ISO-8601 ???? ??? (2026-01-05T22:25:10.199)

  jpa:
    database: postgresql # DB ?? ??
    hibernate:
      ddl-auto: validate # ??? ?? ??/?? ??
    properties:
      hibernate:
        format_sql: true # SQL ??? ?? ?? ??
        jdbc:
          batch_size: 1000       # 1000개씩 모아서 DB에 보냄
          order_inserts: true      # 같은 테이블 insert끼리 묶어서 속도 향상
          order_updates: true      # 같은 테이블 update끼리 묶음
    open-in-view: false # ????? Controller?? ?? ?? ??. N+1 ??? ????? ???? ? (?? ??)


logging:
  level:
    root: info # ?? ?? ??: INFO

springdoc:
  swagger-ui:
    path: /api-docs-ui.html # Swagger UI ??: /api-docs-ui.html
    tags-sorter: alpha # ?? ??: ???
    operations-sorter: method # API ??: HTTP ??? ??
    display-request-duration: true # ?? ?? ?? ??
    doc-expansion: list # ?? ?? ?? (none, list, full)

  api-docs:
    path: /my-api # OpenAPI JSON ??: /my-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers # ??? ??? Actuator ?????
  endpoint:
    health:
      show-details: always # health ?? ?? ?? ??. ?? ????? always, ????? when-authorized
  info:
    env:
      enabled: false # ???? ?? /actuator/info? ??

# /actuator/info ? ???? ?? ??
info:
  app:
    name: monew
    description: ?? ??? ? ???
    version: 1.0.0
    encoding: UTF-8
    java-version: 17
    spring-version: 3.5.9
